# -*- coding: utf-8 -*-
"""word_segmentation_colab_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohlqmw7wESBuMvpYphGHJD2mXU_W4qDs

# MH4.2 — Thai Word Segmentation
**Approach 2: XLM-RoBERTa + fine-tune บน LST20**  
Super AI Engineer Season 6

## 0. Mount Drive & Install
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers datasets seqeval -q

"""## Config"""

import os, json
import numpy as np
import pandas as pd
import torch
from datasets import Dataset, load_dataset
from transformers import (
    AutoTokenizer, AutoModelForTokenClassification,
    TrainingArguments, Trainer, DataCollatorForTokenClassification
)
from seqeval.metrics import f1_score as seqeval_f1

INPUT_PATH  = "/content/drive/MyDrive/Colab/ss6_mh4.2"
OUTPUT_PATH = "/content/drive/MyDrive/Colab/ss6_mh4.2"
MODEL_NAME  = "xlm-roberta-base"

LABEL2ID = {"B_WORD": 0, "I_WORD": 1, "E_WORD": 2}
ID2LABEL = {v: k for k, v in LABEL2ID.items()}
print("GPU:", torch.cuda.is_available())
print("Input files:", os.listdir(INPUT_PATH))

"""## 1. Load LST20 corpus (HuggingFace)"""

print("Downloading plukio/modified_lst20 ...")
lst20 = load_dataset("plukio/modified_lst20")
print(lst20)
print("\nRow แรก (keys):", list(lst20["train"][0].keys()))

def parse_lst20_hf(split):
    """
    แปลง tokens → BIO char-level
    1 token = 1 คำ  →  B (I...) E
    single-char token → B เท่านั้น
    """
    all_sents = []
    for row in lst20[split]:
        tokens = row["tokens"]
        chars, tags = [], []
        for token in tokens:
            chs = list(token)
            n = len(chs)
            for i, ch in enumerate(chs):
                if ord(ch) <= 32:
                    continue
                chars.append(ch)
                if n == 1:         tags.append("B_WORD")
                elif i == 0:       tags.append("B_WORD")
                elif i == n - 1:   tags.append("E_WORD")
                else:              tags.append("I_WORD")
        if chars:
            all_sents.append((chars, tags))
    return all_sents

train_sents = parse_lst20_hf("train")
val_sents   = parse_lst20_hf("validation")
print(f"Train: {len(train_sents)}, Val: {len(val_sents)}")
print("Sample chars:", train_sents[0][0][:10])
print("Sample tags :", train_sents[0][1][:10])

"""## 2. Tokenize สำหรับ XLM-RoBERTa"""

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
MAX_LEN = 128
print("Tokenizer:", tokenizer.__class__.__name__)

def tokenize_and_align(examples):
    tokenized = tokenizer(
        examples["chars"],
        is_split_into_words=True,
        truncation=True,
        max_length=MAX_LEN,
        padding="max_length",
    )
    all_labels = []
    for i, label_seq in enumerate(examples["tags"]):
        word_ids = tokenized.word_ids(batch_index=i)
        prev_word_id = None
        label_ids = []
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word_id:
                label_ids.append(LABEL2ID[label_seq[word_id]])
            else:
                label_ids.append(-100)
            prev_word_id = word_id
        all_labels.append(label_ids)
    tokenized["labels"] = all_labels
    return tokenized

def sents_to_dataset(sents):
    data = {"chars": [s[0] for s in sents], "tags": [s[1] for s in sents]}
    ds = Dataset.from_dict(data)
    return ds.map(tokenize_and_align, batched=True, remove_columns=["chars","tags"])

print("Tokenizing train...")
train_ds = sents_to_dataset(train_sents)
print("Tokenizing val...")
val_ds   = sents_to_dataset(val_sents)
print("Train:", train_ds)
print("Val  :", val_ds)

"""## 3. Load model & train"""

model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=3,
    id2label=ID2LABEL,
    label2id=LABEL2ID,
    ignore_mismatched_sizes=True,
)
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

def compute_metrics(p):
    preds, labels = p
    preds = np.argmax(preds, axis=2)
    true_preds, true_labels = [], []
    for pred_seq, label_seq in zip(preds, labels):
        tp, tl = [], []
        for p_id, l_id in zip(pred_seq, label_seq):
            if l_id != -100:
                tp.append(ID2LABEL[p_id])
                tl.append(ID2LABEL[l_id])
        true_preds.append(tp)
        true_labels.append(tl)
    return {"f1": seqeval_f1(true_labels, true_preds, average="macro")}

USE_GPU = torch.cuda.is_available()
CKPT_PATH = os.path.join(OUTPUT_PATH, "checkpoints")

training_args = TrainingArguments(
    output_dir=CKPT_PATH,
    num_train_epochs=5,
    per_device_train_batch_size=16 if USE_GPU else 8,
    per_device_eval_batch_size=32 if USE_GPU else 8,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=200,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    logging_steps=100,
    fp16=USE_GPU,
    report_to="none",
)

data_collator = DataCollatorForTokenClassification(tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("Training... (ประมาณ 30-60 นาทีถ้าใช้ GPU)")
trainer.train()

"""## 4. Inference บน ws_test.txt"""

# โหลด test text
test_path = os.path.join(INPUT_PATH, "ws_test.txt")
with open(test_path, "r", encoding="utf-8") as f:
    full_text = f.read()

# กรองเฉพาะ chars ที่ต้อง predict (ord > 32)
test_chars = [ch for ch in full_text if ord(ch) > 32]
print(f"Test chars to predict: {len(test_chars)}")

# โหลด sample_sub
sample_sub = pd.read_csv(os.path.join(INPUT_PATH, "ws_sample_submission.csv"))
print(f"sample_sub: {sample_sub.shape}")

model.eval()
device = torch.device("cuda" if USE_GPU else "cpu")
model.to(device)

CHUNK = 120  # ต่ำกว่า MAX_LEN เผื่อ special tokens

def predict_chunk(char_list):
    """predict BIO tags สำหรับ list of chars (1 chunk)"""
    enc = tokenizer(
        char_list,
        is_split_into_words=True,
        truncation=True,
        max_length=MAX_LEN,
        padding="max_length",
        return_tensors="pt",
    ).to(device)
    with torch.no_grad():
        logits = model(**enc).logits
    preds = logits.argmax(-1).squeeze().cpu().numpy()
    word_ids = enc.word_ids(batch_index=0)
    # map word_id → pred label (เอาแค่ first subword ของแต่ละ char)
    wid_to_pred = {}
    for j, wid in enumerate(word_ids):
        if wid is not None and wid not in wid_to_pred:
            wid_to_pred[wid] = ID2LABEL[int(preds[j])]
    # return ตามลำดับให้ครบทุก char
    return [wid_to_pred[k] for k in sorted(wid_to_pred.keys())]

print(f"Predicting {len(test_chars)} chars in chunks of {CHUNK}...")
all_tags = []
for start in range(0, len(test_chars), CHUNK):
    chunk = test_chars[start:start+CHUNK]
    tags  = predict_chunk(chunk)
    # ถ้า truncate แล้วได้น้อยกว่า chunk → pad ด้วย B_WORD
    if len(tags) < len(chunk):
        tags += ["B_WORD"] * (len(chunk) - len(tags))
    all_tags.extend(tags)
    if start % 6000 == 0:
        print(f"  {start}/{len(test_chars)}")

print(f"Predicted: {len(all_tags)} tags")
assert len(all_tags) == len(test_chars), f"Mismatch {len(all_tags)} vs {len(test_chars)}"
print("✓ Length check passed")

"""## 5. Build & export submission"""

submission = sample_sub.copy()
submission["Predicted"] = all_tags

print("Tag distribution:")
print(submission["Predicted"].value_counts())

valid_tags = {"B_WORD", "I_WORD", "E_WORD"}
invalid = submission[~submission["Predicted"].isin(valid_tags)]
assert len(invalid) == 0, f"Invalid tags: {invalid}"
assert len(submission) == 35182, f"Wrong row count: {len(submission)}"
print(f"✓ Validation passed — {len(submission)} rows")

output_file = os.path.join(OUTPUT_PATH, "submission.csv")
submission.to_csv(output_file, index=False)
print(f"✓ Saved → {output_file}")
submission.head(10)